export const TIPS = [
  "输入 {highlight}@{/highlight} 后跟文件名，可模糊搜索并将文件附加到提示中。",
  "消息以 {highlight}!{/highlight} 开头可直接运行 shell 命令（例如：{highlight}!ls -la{/highlight}）。",
  "按 {highlight}Tab{/highlight} 在 Build（完全访问）和 Plan（只读）代理之间切换。",
  "使用 {highlight}/undo{/highlight} 撤销上一条消息及 OpenCode 所做的文件更改。",
  "使用 {highlight}/redo{/highlight} 恢复之前撤销的消息和文件更改。",
  "运行 {highlight}/share{/highlight} 在 opencode.ai 创建对话的公开链接。",
  "拖放图片到终端可将其作为提示的上下文。",
  "按 {highlight}Ctrl+V{/highlight} 可直接从剪贴板粘贴图片到提示中。",
  "按 {highlight}Ctrl+X E{/highlight} 或 {highlight}/editor{/highlight} 在外部编辑器中编写消息。",
  "运行 {highlight}/init{/highlight} 根据代码库结构自动生成项目规则。",
  "运行 {highlight}/models{/highlight} 或 {highlight}Ctrl+X M{/highlight} 查看和切换可用的 AI 模型。",
  "使用 {highlight}/theme{/highlight} 或 {highlight}Ctrl+X T{/highlight} 预览和切换 50+ 内置主题。",
  "按 {highlight}Ctrl+X N{/highlight} 或 {highlight}/new{/highlight} 开始新的对话会话。",
  "使用 {highlight}/sessions{/highlight} 或 {highlight}Ctrl+X L{/highlight} 列出并继续之前的对话。",
  "运行 {highlight}/compact{/highlight} 在接近上下文限制时压缩长会话。",
  "按 {highlight}Ctrl+X X{/highlight} 或 {highlight}/export{/highlight} 将对话保存为 Markdown。",
  "按 {highlight}Ctrl+X Y{/highlight} 复制助手的最后一条消息到剪贴板。",
  "按 {highlight}Ctrl+P{/highlight} 查看所有可用的操作和命令。",
  "运行 {highlight}/connect{/highlight} 添加 75+ 支持的 LLM 提供商的 API 密钥。",
  "默认前导键是 {highlight}Ctrl+X{/highlight}；与其他键组合可快速操作。",
  "按 {highlight}F2{/highlight} 快速切换最近使用的模型。",
  "按 {highlight}Ctrl+X B{/highlight} 显示/隐藏侧边栏面板。",
  "使用 {highlight}PageUp{/highlight}/{highlight}PageDown{/highlight} 浏览对话历史。",
  "按 {highlight}Ctrl+G{/highlight} 或 {highlight}Home{/highlight} 跳转到对话开头。",
  "按 {highlight}Ctrl+Alt+G{/highlight} 或 {highlight}End{/highlight} 跳转到最新消息。",
  "按 {highlight}Shift+Enter{/highlight} 或 {highlight}Ctrl+J{/highlight} 在提示中添加换行。",
  "输入时按 {highlight}Ctrl+C{/highlight} 清空输入框。",
  "按 {highlight}Escape{/highlight} 中途停止 AI 响应。",
  "切换到 {highlight}Plan{/highlight} 代理获取建议而不实际修改文件。",
  "在提示中使用 {highlight}@<代理名>{/highlight} 调用专业子代理。",
  "按 {highlight}Ctrl+X Right/Left{/highlight} 在父子会话间切换。",
  "在项目根目录创建 {highlight}opencode.json{/highlight} 设置项目特定配置。",
  "在 {highlight}~/.config/opencode/opencode.json{/highlight} 放置全局配置。",
  "在配置中添加 {highlight}$schema{/highlight} 可在编辑器中获得自动补全。",
  "在配置中设置 {highlight}model{/highlight} 指定默认模型。",
  "通过配置中的 {highlight}keybinds{/highlight} 部分覆盖任何快捷键。",
  "将任何快捷键设置为 {highlight}none{/highlight} 可完全禁用它。",
  "在配置的 {highlight}mcp{/highlight} 部分配置本地或远程 MCP 服务器。",
  "OpenCode 自动处理需要认证的远程 MCP 服务器的 OAuth。",
  "在 {highlight}.opencode/command/{/highlight} 添加 {highlight}.md{/highlight} 文件定义可复用的自定义提示。",
  "在自定义命令中使用 {highlight}$ARGUMENTS{/highlight}、{highlight}$1{/highlight}、{highlight}$2{/highlight} 实现动态输入。",
  "在命令中使用反引号注入 shell 输出（例如：{highlight}`git status`{/highlight}）。",
  "在 {highlight}.opencode/agent/{/highlight} 添加 {highlight}.md{/highlight} 文件创建专业 AI 角色。",
  "为每个代理配置 {highlight}edit{/highlight}、{highlight}bash{/highlight} 和 {highlight}webfetch{/highlight} 工具的权限。",
  '使用 {highlight}"git *": "allow"{/highlight} 等模式进行细粒度的 bash 权限控制。',
  '设置 {highlight}"rm -rf *": "deny"{/highlight} 阻止危险命令。',
  '配置 {highlight}"git push": "ask"{/highlight} 在推送前要求确认。',
  "OpenCode 使用 prettier、gofmt、ruff 等自动格式化文件。",
  '在配置中设置 {highlight}"formatter": false{/highlight} 禁用所有自动格式化。',
  "在配置中定义带文件扩展名的自定义格式化命令。",
  "OpenCode 使用 LSP 服务器进行智能代码分析。",
  "在 {highlight}.opencode/tool/{/highlight} 创建 {highlight}.ts{/highlight} 文件定义新的 LLM 工具。",
  "工具定义可以调用 Python、Go 等编写的脚本。",
  "在 {highlight}.opencode/plugin/{/highlight} 添加 {highlight}.ts{/highlight} 文件实现事件钩子。",
  "使用插件在会话完成时发送系统通知。",
  "创建插件阻止 OpenCode 读取敏感文件。",
  "使用 {highlight}opencode run{/highlight} 进行非交互式脚本执行。",
  "使用 {highlight}opencode run --continue{/highlight} 继续上次会话。",
  "使用 {highlight}opencode run -f file.ts{/highlight} 通过命令行附加文件。",
  "使用 {highlight}--format json{/highlight} 在脚本中获取机器可读输出。",
  "运行 {highlight}opencode serve{/highlight} 以无头 API 方式访问 OpenCode。",
  "使用 {highlight}opencode run --attach{/highlight} 连接到运行中的服务器以加快执行。",
  "运行 {highlight}opencode upgrade{/highlight} 更新到最新版本。",
  "运行 {highlight}opencode auth list{/highlight} 查看所有已配置的提供商。",
  "运行 {highlight}opencode agent create{/highlight} 进入引导式代理创建流程。",
  "在 GitHub issues/PRs 中使用 {highlight}/opencode{/highlight} 触发 AI 操作。",
  "运行 {highlight}opencode github install{/highlight} 设置 GitHub 工作流。",
  "在 issue 上评论 {highlight}/opencode fix this{/highlight} 自动创建 PR。",
  "在 PR 代码行上评论 {highlight}/oc{/highlight} 进行针对性代码审查。",
  '使用 {highlight}"theme": "system"{/highlight} 匹配终端颜色。',
  "在 {highlight}.opencode/themes/{/highlight} 目录创建 JSON 主题文件。",
  "主题支持深色/浅色两种模式的变体。",
  "在自定义主题中引用 ANSI 颜色 0-255。",
  "使用 {highlight}{env:VAR_NAME}{/highlight} 语法在配置中引用环境变量。",
  "使用 {highlight}{file:path}{/highlight} 在配置值中包含文件内容。",
  "使用配置中的 {highlight}instructions{/highlight} 加载额外的规则文件。",
  "设置代理 {highlight}temperature{/highlight} 从 0.0（专注）到 1.0（创意）。",
  "配置 {highlight}maxSteps{/highlight} 限制每次请求的代理迭代次数。",
  '设置 {highlight}"tools": {"bash": false}{/highlight} 禁用特定工具。',
  '使用 {highlight}"mcp_*": false{/highlight} 禁用某个 MCP 服务器的所有工具。',
  "在每个代理配置中覆盖全局工具设置。",
  '设置 {highlight}"share": "auto"{/highlight} 自动分享所有会话。',
  '设置 {highlight}"share": "disabled"{/highlight} 阻止任何会话分享。',
  "运行 {highlight}/unshare{/highlight} 取消会话的公开访问。",
  "权限 {highlight}doom_loop{/highlight} 防止无限工具调用循环。",
  "权限 {highlight}external_directory{/highlight} 保护项目外的文件。",
  "运行 {highlight}opencode debug config{/highlight} 排查配置问题。",
  "使用 {highlight}--print-logs{/highlight} 标志在 stderr 中查看详细日志。",
  "按 {highlight}Ctrl+X G{/highlight} 或 {highlight}/timeline{/highlight} 跳转到特定消息。",
  "按 {highlight}Ctrl+X H{/highlight} 切换消息中代码块的可见性。",
  "按 {highlight}Ctrl+X S{/highlight} 或 {highlight}/status{/highlight} 查看系统状态信息。",
  "启用 {highlight}tui.scroll_acceleration{/highlight} 获得 macOS 风格的平滑滚动。",
  "通过命令面板（{highlight}Ctrl+P{/highlight}）切换聊天中的用户名显示。",
  "运行 {highlight}docker run -it --rm ghcr.io/anomalyco/opencode{/highlight} 使用容器化版本。",
  "使用 {highlight}/connect{/highlight} 连接 OpenCode Zen 获取精选测试模型。",
  "将项目的 {highlight}AGENTS.md{/highlight} 文件提交到 Git 以便团队共享。",
  "使用 {highlight}/review{/highlight} 审查未提交的更改、分支或 PR。",
  "运行 {highlight}/help{/highlight} 或 {highlight}Ctrl+X H{/highlight} 显示帮助对话框。",
  "使用 {highlight}/details{/highlight} 切换工具执行详情的可见性。",
  "使用 {highlight}/rename{/highlight} 重命名当前会话。",
  "按 {highlight}Ctrl+Z{/highlight} 挂起终端并返回 shell。",
]
